#!/usr/bin/env bash
# configure a running server to listen on port 80

old_port="8080"
new_port="80"
sed -i "s/$old_port default_server/$new_port default_server/g" /etc/nginx/sites-enabled/default
systemctl restart nginx
