#!/usr/bin/env bash
# configures a running server to listen to port 80

new="80 default_server"
old="8080 default_server"
sed -i "s/$old/$new/" /etc/nginx/sites-enabled/default

service nginx restart
