#!/usr/bin/env bash
# creates a file containing its PID
# displays a string indefinitely until any of three signals is received

file="/var/run/myscript.pid"
sudo touch $file
echo $$ > $file

fn_sigterm()
{
	echo "I hate the kill command"
	sudo rm $file
	exit 0
}

fn_sigquit()
{
        sudo rm $file
        exit 0
}

while :
do
	echo "To infinity and beyond"
	trap fn_sigterm 15
	trap 'echo "Y U no love me?!"' 2
	trap fn_sigquit 3
done
