#!/usr/bin/env bash
# displays a string indefinitely with a 2-second delay between each iteration
# a different string when receiving a `SIGTERM` signal

while :
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' 15
done
