#!/usr/bin/env bash
# displays numbers from 1 to 100 in a list format
# replaces a number with a string when it is a multiple of 3 and/or 5

i=1
while ((i < 101))
do
	if ((i % 15 == 0))
	then
		echo "FizzBuzz"
	elif ((i % 3 == 0))
	then
		echo "Fizz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	else
		echo $i
	fi
	((i++))
done
