#!/usr/bin/env bash
# displays a string 10 times using the while loop
# append another string after 9th iteration

i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	if ((i == 8))
		then
		echo "Hi"
	fi
	((i++))
done
