#!/usr/bin/env bash
# loops from 1 to 10 using `while`
# displays different strings for the 4th and 8th iteration
# displays another string for the other iterations

i=1
while [ $i -lt 11 ]
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
