#!/usr/bin/env bash
# displays numbers from 1 to 20 using the while loop and the case statement
# appends strings after the 4th, 9th, and 17th iteration

i=0
while [ $i -lt 20 ]
do
	case $i in
		3)
			echo $i
			echo "bad luck from China"
			;;

		8)
			echo $i
			echo "bad luck from Japan"
			;;

		16)
			echo $i
			echo "bad luck from Italy"
			;;

		*)
			echo $i
			;;
	esac
	((i++))
done
