#!/usr/bin/env bash
# Configure Ubuntu server
# Resolve both 'localhost' and 'facebook.com' to new IP

cp /etc/hosts ~/hosts.new
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
